"use client";

import Link from "next/link";
import { Play } from "lucide-react";
import Button from "@/components/ui/Button";

export default function Hero() {
  return (
    <section
      id="product"
      className="relative min-h-[calc(100vh-4rem)] overflow-hidden px-4 pb-20 pt-16 md:px-8"
    >
      <div
        className="pointer-events-none absolute inset-0"
        style={{
          backgroundImage:
            "radial-gradient(circle at 50% 40%, var(--glow) 0%, transparent 55%), radial-gradient(circle, rgba(255,255,255,0.03) 1px, transparent 1px)",
          backgroundSize: "100% 100%, 24px 24px",
        }}
      />

      <div className="relative mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-2">
        <div>
          <p className="mb-4 font-mono text-xs uppercase tracking-widest text-accent">
            Roblox Studio · AI workspace
          </p>
          <h1 className="font-display text-4xl font-bold uppercase leading-[1.05] tracking-tight sm:text-5xl lg:text-6xl">
            Build Luau
            <br />
            faster than you think.
          </h1>
          <p className="mt-6 max-w-lg text-lg text-text-muted">
            LimeForge turns prompts into production scripts and syncs them to
            your open Roblox place — multi-model AI, chat, versioning.
          </p>
          <div className="mt-8 flex flex-wrap items-center gap-4">
            <Link href="/app">
              <Button glow>Start free</Button>
            </Link>
            <Link href="/app">
              <Button variant="ghost">
                <Play className="h-4 w-4 fill-current" />
                Open demo workspace
              </Button>
            </Link>
          </div>
        </div>

        <div className="rounded-xl border border-bg-elevated bg-bg-secondary p-3 shadow-2xl">
          <div className="grid grid-cols-3 gap-2 text-center font-mono text-[10px] text-text-muted">
            <span className="rounded bg-bg-surface py-2">Chat</span>
            <span className="rounded bg-accent-dim py-2 text-accent">Model ▾</span>
            <span className="rounded bg-bg-surface py-2">Luau out</span>
          </div>
          <pre className="mt-3 max-h-64 overflow-auto rounded-lg border border-bg-elevated bg-bg-primary p-4 font-mono text-[11px] leading-relaxed text-success">
{`-- synced to ServerScriptService
local DataStore = game:GetService("DataStoreService")
local store = DataStore:GetDataStore("DailyRewards_v1")

local function claimReward(player)
  -- generated by claude-sonnet-4-6
end`}
          </pre>
        </div>
      </div>
    </section>
  );
}